# Generated by Django 6.0.1 on 2026-01-29 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('reflection_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hello_count', models.IntegerField(default=0, verbose_name='あいさつ回数')),
                ('thanks_given', models.BooleanField(default=False, verbose_name='ありがとう言えた')),
                ('thanks_received', models.BooleanField(default=False, verbose_name='ありがとう言われた')),
                ('good_thing', models.TextField(blank=True, verbose_name='嬉しかったこと')),
                ('bad_thing', models.TextField(blank=True, verbose_name='嫌だったこと')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日次振り返り',
                'db_table': 'daily_reflections',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(verbose_name='フィードバック文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reflection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reflections.dailyreflection')),
            ],
            options={
                'verbose_name': 'フィードバック',
                'db_table': 'feedback_messages',
            },
        ),
    ]
