# Generated by Django 6.0.1 on 2026-01-31 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('reflection_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='振り返り日付')),
                ('hello_count', models.IntegerField(default=0, verbose_name='あいさつ回数')),
                ('thanks_given', models.BooleanField(default=False, verbose_name='ありがとう言えた')),
                ('thanks_received', models.BooleanField(default=False, verbose_name='ありがとう言われた')),
                ('good_thing', models.TextField(blank=True, verbose_name='嬉しかったこと')),
                ('bad_thing', models.TextField(blank=True, verbose_name='嫌だったこと')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '日次振り返り',
                'db_table': 'daily_reflections',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(verbose_name='フィードバック文')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'フィードバック',
                'db_table': 'feedback_messages',
            },
        ),
    ]
