# Generated by Django 6.0.1 on 2026-01-31 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reflections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedbackmessage',
            name='reflection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='reflections.dailyreflection'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreflection',
            unique_together={('user', 'date')},
        ),
    ]
