# Generated by Django 6.0.1 on 2026-02-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreflection',
            name='answers',
            field=models.JSONField(default=list, help_text='チェックボックスの回答を配列で保存', verbose_name='振り返り質問の回答'),
        ),
    ]
