# Generated by Django 6.0.1 on 2026-01-31 03:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='タスク日付')),
                ('task_title', models.CharField(max_length=100, verbose_name='タスク名')),
                ('task_message', models.TextField(verbose_name='励ましメッセージ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '日次タスク',
                'db_table': 'daily_tasks',
                'ordering': ['-date'],
            },
        ),
    ]
