# Generated by Django 6.0.1 on 2026-01-29 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('task_title', models.CharField(max_length=100, verbose_name='タスク名')),
                ('task_message', models.TextField(verbose_name='励ましメッセージ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '日次タスク',
                'db_table': 'daily_tasks',
                'ordering': ['-date'],
            },
        ),
    ]
