# Generated by Django 6.0.1 on 2026-02-02 02:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='1-50', verbose_name='レベル')),
                ('theme', models.CharField(choices=[('alone', '自分の部屋で、一人で'), ('family', '家の中で、家族と'), ('outside', '家の外へ'), ('stay_outside', '外で過ごす'), ('interact', '人と関わる'), ('exercise', '体を動かす'), ('challenge', '新しいことに挑戦')], max_length=20, verbose_name='テーマ')),
                ('title', models.CharField(max_length=100, verbose_name='タスク名')),
                ('message', models.TextField(help_text='ユーザーに表示する優しいメッセージ', verbose_name='メッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'タスクテンプレート',
                'verbose_name_plural': 'タスクテンプレート',
                'db_table': 'task_templates',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailytask',
            options={'verbose_name': '日次タスク', 'verbose_name_plural': '日次タスク'},
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task_message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.tasktemplate', verbose_name='元のテンプレート'),
        ),
    ]
