# Generated by Django 6.0.1 on 2026-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktemplate_alter_dailytask_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='changed_templates',
            field=models.JSONField(default=list, verbose_name='変更済みテンプレートIDリスト'),
        ),
    ]
