# Generated by Django 6.0.1 on 2026-02-02 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_dailytask_changed_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktemplate',
            name='reflection_questions',
            field=models.JSONField(default=list, help_text='YES/NO形式の質問を3つまで', verbose_name='振り返り質問'),
        ),
    ]
