# Generated by Django 6.0.1 on 2026-01-31 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mode',
            field=models.CharField(blank=True, choices=[('restart', '再始動'), ('keep', '現状維持')], max_length=10, null=True, verbose_name='モード'),
        ),
    ]
