# Generated by Django 6.0.1 on 2026-01-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reflection_time',
            field=models.TimeField(default='20:00:00', verbose_name='振り返り時刻'),
        ),
        migrations.AddField(
            model_name='user',
            name='task_time',
            field=models.TimeField(default='05:00:00', verbose_name='タスク表示時刻'),
        ),
    ]
