# Generated by Django 6.0.1 on 2026-02-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_reflection_time_user_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_task_date',
            field=models.DateField(blank=True, null=True, verbose_name='最終タスク実施日'),
        ),
    ]
